language: dart

dart:
  - stable
  - dev

install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor

before_script: cd project

script:
  - flutter packages get
  - flutter test --no-pub test/

cache:
  directories:
    - "$HOME/.pub-cache"
